pull_request_rules:
  - name: Automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
    actions:
      merge:
        method: rebase
  
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: rebase
  
  - name: Automatic merge on getting the label ready-to-merge
    conditions:
      - label=ready-to-merge
    actions:
      merge:
        method: rebase
